# Generated by Django 2.2 on 2019-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190504_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='11.jpg', upload_to='profile_pics'),
        ),
    ]
